sudo: required

services:
- docker

addons:
  apt:
    packages:
      - build-essential

language: ruby

rvm:
- 2.2.3
- 2.1.6
- 2.0.0
- 1.9.3
- 1.9.2
- ruby-head

matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: 1.9.2
