sudo: required

services:
- docker

addons:
  apt:
    packages:
      - build-essential
      - zlib1g-dev

language: ruby

rvm:
- 2.1.7
- 2.0.0
- 1.9.3
- ruby-head

env:
  global:
    - KITCHEN_ARGS="--destroy=always"
  matrix:
    - KITCHEN_REGEXP=centos
    - KITCHEN_REGEXP=debian
    - KITCHEN_REGEXP=ubuntu

matrix:
  allow_failures:
  - rvm: ruby-head
